security:
  oauth2:
    client:
      clientId: ${localOauthClientId}
      clientSecret: ${localOauthClientSecret}
      grantTypes: ${localOauthClientGrantTypes}
      scopes: ${localOauthClientScopes}
    resource:
      id: ${localOauthResourceId}
  water-auth-user:
    username: ${localUserName}
    password: ${localUserPassword}
    role: ${localUserRole}
    email: ${localUserEmail}
    details:
      office-state: ${localUserOfficeState}

server:
  context-path: ${localContextPath:/auth}
