security:
  basic:
    enabled: false

samlIdpMetadataLocation: classpath:/metadata/metadata.xml
samlAuthnRequestEntityId: entityId
samlAuthnRequestProviderName: providerName
samlGroupAttributeName: http://schemas.xmlsoap.org/claims/Group
samlEmailAttributeName: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress
samlUsernameAttributeName: http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname
keystoreLocation: classpath:/security/keystore.jks
keystoreDefaultKey: default
keystoreTokenSigningKey: oauth
keystorePassword: changeit
loginSuccessTargetUrl: /
loginErrorTargetUrl: /auth-error
logoutSuccessTargetUrl: /out
dbDriverClassName: com.mysql.jdbc.Driver
dbSchemaType: mysql
dbInitializerEnabled: true

server:
    port: ${serverPort:8443}
    ssl:
        key-store: ${keystoreLocation}
        key-store-password: ${keystorePassword}
        key-password: ${keystorePassword} 
        
logging:
  level:
    org:
      springframework: DEBUG