security:
  basic:
    enabled: false

samlIdpMetadataLocation: classpath:/metadata/metadata.xml
samlAuthnRequestEntityId: entityId
samlAuthnRequestProviderName: providerName
samlGroupAttributeName: http://schemas.xmlsoap.org/claims/Group
samlEmailAttributeName: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress
samlUsernameAttributeName: http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname
keystoreLocation: classpath:/security/keystore.jks
keystoreDefaultKey: default
keystoreTokenSigningKey: oauth
keystorePassword: changeit
loginSuccessTargetUrl: /
loginErrorTargetUrl: /auth-fail
logoutSuccessTargetUrl: /

server:
    port: ${serverPort:8443}
    ssl:
        key-store: ${keystoreLocation}
        key-store-password: ${keystorePassword}
        key-password: ${keystorePassword} 
        
spring:
 session:
   store-type: jdbc
   timeout: 43200 #12 hours
   jdbc:
     table-name: SPRING_SESSION